groups:
    - bash
    - developer
    - smartie
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - applications::istatmenus4
        - applications::kaleidoscope
        - applications::omnigraffle
        - applications::vlc
        - applications::alfred
        - applications::totalfinder
        - applications::cord
        - applications::bartender
        - applications::hhvm
        - skylab::default
        - sudo::default
        - applications::vmware_fusion
        - applications::vagrant
        - osxdefaults::set_computer_name
attributes:
    git:
        name: Josh Schubkegel
        email: jschub@gmail.com
    osxdefaults:
        computername: AirSchub
    authorization:
        sudo:
            users:
                - jschub
            passwordless: true
            include_sudoers_d: true
